# Frames creation

create txt file of videos paths

In [ ]:
import os

text_file = open("videosfront.txt", "w")
path = "/content/drive/MyDrive/PSL Schools Dataset/front"
dirs = os.listdir(path)

for person in os.listdir(path):
  for video in os.listdir(path+"/"+person):
    video_name = path+"/"+person+"/"+video
    text_file.write(video_name+"\n")
    print(video_name)

text_file.close()


Create Training frames

In [ ]:
import cv2

def getFrame(sec, frame_name, vidcap, count):
    vidcap.set(cv2.CAP_PROP_POS_MSEC,sec*1000)
    hasFrames, image = vidcap.read()

    if hasFrames:
        #image = cv2.resize(image, dsize=(120,120))              #resize image to 120x120
        filename = '/content/drive/MyDrive/VideoFrames/TrainingFrames/' + frame_name + "_%d.jpg" % count
        cv2.imwrite(filename, image)    # save frame as JPG file

    return hasFrames

In [ ]:
# open the .txt file which have names of training videos
f = open("/content/drive/MyDrive/PSL dataset/trainingVideosFront2.txt", "r")
temp = f.read()
videos = temp.split('\n')


# storing the frames from training videos
for video in videos:

    vidcap = cv2.VideoCapture(video)
    sec = 0
    frameRate = 1/6  # it will capture image in each 1/6th second
    count = 1
    #frame_name = video.replace('/', '_')
    video_array = video.split("/")
    print(video)

    frame_name = video_array[-3] + "_" + video_array[-2] + "_" + video_array[-1][:-4]
    print(frame_name+"\n")
    
    success = getFrame(sec, frame_name, vidcap, count)

    while success:
        count = count + 1
        sec = sec + frameRate
        sec = round(sec, 2)
        success = getFrame(sec, frame_name, vidcap, count)

/content/drive/MyDrive/PSL Schools Dataset/front/Student5 repeat/sentence2.mp4
front_Student5 repeat_sentence2

/content/drive/MyDrive/PSL Schools Dataset/front/Student5 repeat/sentence3.mp4
front_Student5 repeat_sentence3

/content/drive/MyDrive/PSL Schools Dataset/front/Student5 repeat/sentence4.mp4
front_Student5 repeat_sentence4

/content/drive/MyDrive/PSL Schools Dataset/front/Student5 repeat/sentence5.mp4
front_Student5 repeat_sentence5

/content/drive/MyDrive/PSL Schools Dataset/front/Student5 repeat/sentence6.mp4
front_Student5 repeat_sentence6

/content/drive/MyDrive/PSL Schools Dataset/front/Student5 repeat/sentence7.mp4
front_Student5 repeat_sentence7

/content/drive/MyDrive/PSL Schools Dataset/front/Student5 repeat/sentence8.mp4
front_Student5 repeat_sentence8

/content/drive/MyDrive/PSL Schools Dataset/front/Student5 repeat/sentence9.mp4
front_Student5 repeat_sentence9

/content/drive/MyDrive/PSL Schools Dataset/front/Student5 repeat/sentence10.mp4
front_Student5 repeat_se

Create Testing Frames

In [ ]:
import cv2

def getFrame(sec, frame_name, vidcap, count):
    vidcap.set(cv2.CAP_PROP_POS_MSEC,sec*1000)
    hasFrames, image = vidcap.read()

    if hasFrames:
        #image = cv2.resize(image, dsize=(120,120))              #resize image to 120x120
        filename = '/content/drive/MyDrive/VideoFrames/TestingFrames/' + frame_name + "_%d.jpg" % count
        cv2.imwrite(filename, image)    # save frame as JPG file

    return hasFrames

In [ ]:
# open the .txt file which have names of training videos
f = open("/content/drive/MyDrive/PSL dataset/testingVideosFront2.txt", "r")
temp = f.read()
videos = temp.split('\n')


# storing the frames from training videos
for video in videos:

    vidcap = cv2.VideoCapture(video)
    sec = 0
    frameRate = 1/6  # it will capture image in each 1/6th second
    count = 1
    video_array = video.split("/")
    print(video)

    frame_name = video_array[-3] + "_" + video_array[-2] + "_" + video_array[-1][:-4]
    print(frame_name+'\n')

    success = getFrame(sec, frame_name, vidcap, count)

    while success:
        count = count + 1
        sec = sec + frameRate
        sec = round(sec, 2)
        success = getFrame(sec, frame_name, vidcap, count)

/content/drive/MyDrive/PSL Schools Dataset/front/Student5 repeat/sentence1.mp4
front_Student5 repeat_sentence1

/content/drive/MyDrive/PSL Schools Dataset/front/Student3/sentence2.mp4
front_Student3_sentence2

/content/drive/MyDrive/PSL Schools Dataset/front/Teacher/sentence3.mp4
front_Teacher_sentence3

/content/drive/MyDrive/PSL Schools Dataset/front/Student4/sentence4.mp4
front_Student4_sentence4

/content/drive/MyDrive/PSL Schools Dataset/front/Teacher/sentence5.mp4
front_Teacher_sentence5

/content/drive/MyDrive/PSL Schools Dataset/front/Student5/sentence6.mp4
front_Student5_sentence6

/content/drive/MyDrive/PSL Schools Dataset/front/Student4 repeat/sentence7.mp4
front_Student4 repeat_sentence7

/content/drive/MyDrive/PSL Schools Dataset/front/Student2 repeat/sentence8.mp4
front_Student2 repeat_sentence8

/content/drive/MyDrive/PSL Schools Dataset/front/Student2/sentence9.mp4
front_Student2_sentence9

/content/drive/MyDrive/PSL Schools Dataset/front/Student5 repeat/sentence12.mp4


# Convert Test data toNumPy arrays

In [ ]:
import cv2
import numpy as np
import os
import pickle

In [ ]:
def toNumpy(dir, filename):
    out = np.empty([0,43200], np.uint8, 'C')
    print(out.shape)

    label = []
    diction = {}
    dirs = os.listdir(dir)

    for img in dirs:
      print(img)
      path = dir+"/"+img

      if path.endswith(".png"):
        I = cv2.imread(path)
        I = cv2.resize(I, dsize=(120,120))
        im = (np.array(I))
        r = im[:, :, 0].flatten()
        g = im[:, :, 1].flatten()
        b = im[:, :, 2].flatten()
        a = [list(r) + list(g) + list(b)]
        b = np.asarray(a)
        
        #label_name = int((dir.split('/')[-1]).split('_')[-1][8:])
        #print(label_name)

        out = np.append(out, b, axis=0)
        #label.append(label_name)

    #diction['data'] = out
    #diction['labels'] = label
    print(out)
    print('shape = ' + str(out.shape))
    #print(label)
    #print(len(label))


    with open('/content/drive/MyDrive/PSL dataset/'+filename, 'wb') as fout:
        pickle.dump(out, fout)

In [ ]:
toNumpy('/content/drive/MyDrive/VideoFrames/bg removal/Moiz_sentence9','Moiz_sentence9')

(0, 43200)
7.png
6.png
8.png
2.png
9.png
5.png
11.png
4.png
3.png
1.png
14.png
13.png
12.png
10.png
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
shape = (14, 43200)
